### PR TITLE
ForeignKey error: metadata displayed in note

### LINKED ISSUE #973: Add ForeignKey fields in ForeignKey Error note
# Overview

When a ForeignKey Error is reported there is no way to know which ForiegnKey didn't validate.
Yet one resource can have multiple ForeignKeys attached to it.
It would help to add the Foreign Key Fields in the Error note.

I made a small edit in my local version of fircitonless-py to add those fields in the error note like this : 
```
{
...
"note": "currency;year;reporting not found in the lookup table as currency;year;reporting",
...
"note": "partner not found in the lookup table as original_name",
...
}
```

Fields are ; separated if multiple and both target and source fields are displayed.

But maybe those should be added as variables in the error objects rather than in the note string?

I can submit a PR if you validate the concept and needs.
It was mandatory in my case to understand what was the issue.

### PR DESCRIPTION
**Pull request by paulgirard**
FK error note are enhanced to help dat curator
- fields from soruce and target table are added
- values from source table
- reference table name
- Tests added from multi field FK validation and note format

Those information are useful when curating from validation errors.
fixes #973

- fixes #<issue-number>

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by paulgirard** [comment]
Mmm something went wrong with the CI apparently...
Let me know If I can help.

**Comment by enioarz** [comment]
Is this feature being considered? I was about to do a similar merge request but figure out this is already here.

**Comment by roll** [comment]
Hi, @aivuk can you please take a look?

**Comment by enioarz** [comment]
I have a slight modification of this feature but I can't update this pull request becasue it is in a foreign repo, is it ok if I make a different pull request?

@paulgirard  are you still working on this?

**Comment by aivuk** [comment]
> I have a slight modification of this feature but I can't update this pull request becasue it is in a foreign repo, is it ok if I make a different pull request?
> 
> @paulgirard are you still working on this?

No problem in creating a new pull, but then I will close this one after you created the new one

**Comment by enioarz** [comment]
> > I have a slight modification of this feature but I can't update this pull request becasue it is in a foreign repo, is it ok if I make a different pull request?
> > @paulgirard are you still working on this?
> 
> No problem in creating a new pull, but then I will close this one after you created the new one

I did a pull request with my work account, I did not take over the tests however.

**Review by roll — APPROVED** [review]
Sorry for a long review. I think the lining fails I'll fix it after merging

**Comment by paulgirard** [comment]
Sorry for the late reply.
Yes I still needs those inputs in my project. I did a minimal proposition here. @Eugenio2192 your inputs are more than welcome but I see you don't need me on this actually ;-)
Extended error API is a good thing to do I think.

**Pull request merged**
