### PR TITLE
Removed function wrap_text_to_colwidths

### LINKED ISSUE #1150: Migrate to tabulate@0.8.10
# Overview

I hope we can now drop "wrap_text_to_colwidths" backport

### PR DESCRIPTION
**Pull request by shashigharti**
- Removed backported code for tabulate.
- fixes #1150

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by shashigharti** [comment]
@roll it is ready for the review!

**Review by roll — CHANGES_REQUESTED** [review]
@shashigharti 
We also need to ensure minimal version of tabulate in setup.py

**Comment by shashigharti** [comment]
> @shashigharti We also need to ensure minimal version of tabulate in setup.py

Sorry I forgot to push that change. I will update it

**Comment by shashigharti** [comment]
@roll  thanks! I have updated the version of the library.

**Review by roll — APPROVED** [review]
Thanks!

**Pull request merged**
