### PR TITLE
Now the package errors show all the metadata errors

### PR DESCRIPTION
**Pull request by areleu**
There was an indentation that was hiding all the json schema errors. I think the default messages can get some clarity maintenance but now that they are there debugging schemas can be made easier.

### CODE REVIEW

**Comment by roll** [comment]
Thanks @areleu!

Hi @shashigharti can you please review and maybe add a test clearly showcasing the problem?

**Comment by shashigharti** [comment]
Thanks @areleu!. It looks good to me!

**Comment by shashigharti** [comment]
@areleu could you make fixes for failing 'checks' ? Thanks!

**Comment by areleu** [comment]
> @areleu could you make fixes for failing 'checks' ? Thanks!

I just pushed the fixes, let me know if they work. @shashigharti

**Comment by shashigharti** [comment]
Thanks @areleu, this is fixed in version v5

**Comment by shashigharti** [comment]
Thanks @areleu, this is fixed in version v5

**Pull request closed without merging**
