### PR TITLE
create docker files to run the documentation portal locally

### PR DESCRIPTION
**Pull request by augusto-herrmann**
# Overview

Running the documentation portal inside a Docker container should make it easier for people contributing to documentation to make sure it is building properly before doing a PR.

##  How to run with Docker

With Docker and Docker Compose installed, first build the docker container with:

```
docker build --rm -t frictionless-docs .
```

then, every time you want to run the documentation portal locally, run:

```
docker-compose up
```

then open http://localhost:3000 on your browser to see the portal.

## TODO

This PR is not yet ready for merge. For some reason, port 3000 in localhost is not responding, even though the service is running inside the container and the port is exposed in the `Dockerfile` and listed on `docker-compose.yml`. :thinking: 

---

Please preserve this line to notify @roll (lead of this repository)

### CODE REVIEW

**Comment by augusto-herrmann** [comment]
Done. I needed to specify the host as "0.0.0.0" in docker compose in order for the Docusaurus application to serve outside the container.

**Comment by augusto-herrmann** [comment]
Why are the tests failing if I'm only adding new docker files? :thinking:

**Comment by roll** [comment]
Hi, I got the same yesterday. Seems to be breaking changes in sql alchemy

**Comment by augusto-herrmann** [comment]
I see. It seems sqlalchemy version is not pinned on `setup.py`.

Anyway, this PR seems safe and independent from the issue with the tests.

**Comment by roll** [comment]
Thanks! It's great I will review and merge soon

**Review by roll — APPROVED** [review]
Thanks!

**Pull request merged**
