### PR TITLE
Update contributing document

### LINKED ISSUE #1413: Document how to reproduce portals' tests
# Overview

@shashigharti can you please add some info to https://framework.frictionlessdata.io/docs/codebase/contributing.html on how to reproduce the cassettes locally?

### PR DESCRIPTION
**Pull request by shashigharti**
Add info about reproducing the cassettes locally

- fixes #1413

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by shashigharti** [comment]
@roll it is ready for review. Thanks!

**Review by roll — CHANGES_REQUESTED** [review]
Thanks, @shashigharti it's a great addition

But what we also would like to have is a short explanation of how to setup CKAN, Zenodo, and Github testing.

Considering all the cassettes are removed, how could one recover all of them? Do we need to run ckan docker, what zenodo credentials we need to provide etc. Does it make sense? =)

**Comment by shashigharti** [comment]
yes it does. thanks! . I will make the changes.

**Comment by roll** [comment]
Thanks!

**Comment by shashigharti** [comment]
@roll I have updated the document and it is ready for review!

**Review by roll — APPROVED** [review]
Thanks!

We might need to add more info on how to run a custom ckan info (cc @aivuk) but it looks quite good for now

**Comment by shashigharti** [comment]
@roll I used this to setup local instance https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html. Shall I add this link there in the doc?

**Comment by aivuk** [comment]
I think the best approach would be to use https://github.com/okfn/docker-ckan, that come already with everything configured (nginx, postgresql, redis and solr)

**Comment by roll** [comment]
Thanks @aivuk @shashigharti, I've added it to the docs

**Pull request merged**
