### PR TITLE
Fix for datetime field conversion for pandas format

### LINKED ISSUE #1482: Pandas 2: time conversion fails
# Overview

FAILED tests/formats/pandas/test_parser.py::test_pandas_parser_write_timezone

```
frictionless.exception.FrictionlessException: [source-error] The data source has not supported or has inconsistent contents: <class 'datetime.time'> is not convertible to datetime, at position 1
```

### LINKED ISSUE #1488: Exception thrown when attempting to write a Date-time field with timezone to Parquet
# Overview

Version: frictionless 5.10.5

Attempting to write a Resource to a Parquet file fails if the file contains a Date-time field with a timezone.

Example:
```
>>> r = Resource([["a"], ["2025-08-24T15:00:00Z"]])
>>> r.write("test_dt.parquet")
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/util.py", line 427, in get_column_metadata
    pd.Series([pd.to_datetime('now', utc=True)]).dt.tz_localize(stz)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/accessor.py", line 112, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/indexes/accessors.py", line 128, in _delegate_method
    result = method(*args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/indexes/datetimes.py", line 279, in tz_localize
    arr = self._data.tz_localize(tz, ambiguous, nonexistent)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/arrays/_mixins.py", line 86, in method
    return meth(self, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 1035, in tz_localize
    raise TypeError("Already tz-aware, use tz_convert to convert.")
TypeError: Already tz-aware, use tz_convert to convert.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/frictionless/resource/resource.py", line 926, in write
    parser.write_row_stream(self)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/frictionless/formats/parquet/parser.py", line 46, in write_row_stream
    platform.fastparquet.write(self.resource.normpath, source.to_pandas())
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/writer.py", line 1294, in write
    fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/writer.py", line 890, in make_metadata
    get_column_metadata(data[column], column, object_dtype=oencoding))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/test-Vr6uvig8-py3.10/lib/python3.10/site-packages/fastparquet/util.py", line 434, in get_column_metadata
    raise ValueError("Time-zone information could not be serialised: "
ValueError: Time-zone information could not be serialised: tzutc(), please use another
```

Issue cannot be reproduced if the timezone is removed:
```
>>> r = Resource([["a"], ["2025-08-24T15:00:00"]])
>>> r.write("test_dt.parquet")
{'name': 'test_dt',
 'type': 'table',
 'path': 'test_dt.parquet',
 'scheme': 'file',
 'format': 'parquet',
 'mediatype': 'appliction/parquet'}
```

### PR DESCRIPTION
**Pull request by shashigharti**
- fixes #1488
- fixes #1482

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by roll** [comment]
Hi @shashigharti, honestly I don't know =) it looks good as you haven't changed any existing tests and added a new one that covers the bug. BTW is there any relation to #1482?

**Comment by shashigharti** [comment]
> BTW is there any relation to #1482?

Not sure. I haven't tested it yet. I will update here once I test.

**Comment by shashigharti** [comment]
@roll I have added the fix(for issue# 1482 also) and it is ready for review. But I am not quite sure if the solution is right because of the following characteristics of the problem:

The error occurs when timezone(tzinfo) set to `tzutc()` when the **UTC** offset is zero. 
```
data_rows = [[datetime(2020, 1, 1, 15, 0, tzinfo=timezone.utc),  time(15, 0, tzinfo=tzutc())]]
df = pd.DataFrame(data_rows, columns=[["datetime", "time"]])
for pk, item in df.iterrows():
    print(item)
```

But again if I use the same without pairing with other columns it works fine:
```
data_rows = [[time(15, 0, tzinfo=tzutc())]]
df = pd.DataFrame(data_rows, columns=[["time"]])
for pk, item in df.iterrows():
    print(item)
```

Thank you!

**Review by roll — APPROVED** [review]
It seems to be we're back for passing the tests and also the new parquet tests. So we should be fine. Great thanks!

**Pull request merged**
