### PR TITLE
Add tests for ckan integration

### LINKED ISSUE #1344: Tests for CKAN as a portal integration
# Overview

Add tests for ckan plugin(data portal).

### PR DESCRIPTION
**Pull request by shashigharti**
- Add tests
- Add data
- Marked test as 'skip' for functionalities that did not work.

- fixes #1344

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by shashigharti** [comment]
@aivuk @roll it is ready for the review!.

**Comment by aivuk** [comment]
I'm looking at it @shashigharti

**Comment by roll** [comment]
Hi @shashigharti, shall it be promoted from WIP?

**Comment by shashigharti** [comment]
> Hi @shashigharti, shall it be promoted from WIP?

Yes, I have changed.

**Comment by roll** [comment]
Thanks @shashigharti, I will review.

@aivuk Can you please finish your review as well?

**Review by aivuk — APPROVED** [review]
Looks good to me! Good job @shashigharti

**Comment by shashigharti** [comment]
Thanks!

**Review by roll — APPROVED** [review]
Amazing thanks!

**Pull request merged**
