### PR TITLE
1067/generates summary of resource data

### LINKED ISSUE #1067: Implement `resource.analyze` function and CLI command
# Overview

> https://frictionlessdata.slack.com/archives/C0369HZ2SLT/p1651844750785019

_Is there any tooling around that does more than describe to analyse the data.  For example tools that would give you distributions for number fields, most common word statistics for text fields, distinct counts, counts for fields that are not blank, most common categories used, and many others?   Essentially statistics that are currently not in the tablular data package resource specification?  Also could help detect more kinds of data formats.
As example of some of this could be done by pandas describe function https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html, however there is a lot more potential than that.
Also is it ok to add suche extra statistics to resouces without causing validation errors?
I am thinking such tooling would be interesting as it could give greater insight into the data before the need to analyse it._

# Plan
- [ ] @shashigharti @aivuk We need to brainstorm the analytics output format and contents. We can probably use the `Stats` class (`resource.stats`) as a target (alternatively, might be a `validate/report` part)
- [ ] implement `resource.analyze`
- [ ] implement `package.analyze` (reusing the above)
- [ ] expose in the CLI (reusing above)

### PR DESCRIPTION
**Pull request by shashigharti**
-  Added analyze function for resource and package
-  Added tests
- fixes #1067

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by shashigharti** [comment]
@roll it is ready for review!

**Review by roll — CHANGES_REQUESTED** [review]
Thanks @shashigharti!

It looks really good! Can you please:
- switch to "camelCase" naming for the analysis report like "field_stats" to "fieldStats" (that's the way we use for the declarative metadata) (of course, actual field names should stay the same) 
- add a note to docstrings that these methods are experimental

Then let's merge it and we will finish the development (action/CLI) in v5 -- so let's keep it not announced for now

**Comment by shashigharti** [comment]
Thank you @roll!

I have made the changes as per your feedback. It is ready for the review.

**Review by roll — APPROVED** [review]
Great work!

**Pull request merged**
