### PR TITLE
Fixed ambiguous truth values of arrays

### LINKED ISSUE #1245: V5: Pandas and numpy array errors when validating resources
# Overview

If you run the validate command in a resource that has pandas dataframes it will fail at 

https://github.com/frictionlessdata/framework/blob/86318877da848fd348070c08b4dee86b1e18adf7/frictionless/resource/resource.py#L330

and

https://github.com/frictionlessdata/framework/blob/86318877da848fd348070c08b4dee86b1e18adf7/frictionless/resource/resource.py#L1247

and

https://github.com/frictionlessdata/framework/blob/86318877da848fd348070c08b4dee86b1e18adf7/frictionless/resource/resource.py#L1104

and

https://github.com/frictionlessdata/framework/blob/86318877da848fd348070c08b4dee86b1e18adf7/frictionless/resource/resource.py#L895

I will do a pull requests fixing those but there are probably more.

### PR DESCRIPTION
**Pull request by areleu**
- fixes #1245

The description is in the issue.

### CODE REVIEW

**Comment by areleu** [comment]
I keep having this issue now and then. I rebased to main, hope you can include it soon.

**Comment by shashigharti** [comment]
Thanks! @areleu

This looks good to me! and works for dataframe. It would be nice if we could add a test highlighting the bug and maybe also adding a short comment in code just to describe the change.

**Comment by areleu** [comment]
I added a test for the particular problem. I see no point on adding comments on each one of the changes, it would clutter the code and there were already similar checks in other lines like [1213 ](https://github.com/frictionlessdata/framework/blob/5e092abae1167c6d8e452cb934b9f202ecf28801/frictionless/resource/resource.py#L1213).

**Comment by shashigharti** [comment]
Thanks @areleu 

@roll this looks good to me!

**Review by roll — APPROVED** [review]
Thanks a lot @areleu @shashigharti !

**Pull request merged**
