### PR TITLE
Made private properties public for detector

### LINKED ISSUE #1015: Ability to set Detector properties
# Overview

See https://github.com/frictionlessdata/frictionless-py/issues/1014

Currently, it's not possible to set Detector properties after an instance is created:

```python
detector = Detector(buffer_size=100)
detector.buffer_size = 200 # wont work
```

We want to make it settable probably using an approach we use for other classes in Frictionless (for example, for the Field class):

```python
    def __setattr__(self, name, value):
        if name == "schema":
            self.__schema = value
        else:
            return super().__setattr__(name, value)
```

The list of properties we want to be able to set (all of the current):
- buffer_size
- sample_size
- encoding_function
- encoding_confidence
- field_type
- field_names,
- field_confidence
- field_float_numbers
- field_missing_values
- schema_sync
- schema_patch

# Plan
- [ ] implement property setter using `__setattr__` for Detector 
- [ ] write a few tests for the new functionality in `tests/test_detector.py`
- [ ] create a PR and request a review from @roll

### PR DESCRIPTION
**Pull request by shashigharti**
Added getters and setters for private properties
-  Added getters and setters for all private fields
-  Added tests for the above code

Added example for encoding_function (#1020)
- update docs for encoding_function and confidence
- updated missing docstring for encoding_function and confidence

- fixes #1015 #1020
---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Review by aivuk — COMMENTED** [review]
Your test code need some changes. Is there a reason why you are always doing something like:
```

    detector = Detector(sample_size=1000)
    assert detector.sample_size == 1000
    detector.sample_size = 1000
    assert detector.sample_size == 1000
```
If the this pass ```assert detector.sample_size == 1000``` the next line is redundant ```   detector.sample_size = 1000```. And after this step, why are you testing again for the ``` assert detector.sample_size == 1000```?

**Review by aivuk — COMMENTED** [review]
In your setter logic you could have used the standard Python setattr method. Instead of a lot of if/else you can have something:

`setattr(self, '_{}'.format(name), value)`

**Comment by roll** [comment]
@shashigharti Yea you might mistakenly have used the same value for testing whether we can set a different value. 

No worries it just needs a quick fix

**Comment by shashigharti** [comment]
Hi @aivuk 

It is because It is testing two aspects one is:

- passing params during initialization
- setting private properties using setters.

I think I am using same values so I will change it to different value for second one.

**Comment by roll** [comment]
> In your setter logic you could have used the standard Python setattr method. Instead of a lot of if/else you can have something:
> 
> `setattr(self, '_{}'.format(name), value)`

@aivuk will it work for private attributes?

**Comment by shashigharti** [comment]
> In your setter logic you could have used the standard Python setattr method. Instead of a lot of if/else you can have something:
> 
> `setattr(self, '_{}'.format(name), value)`

This may not work as I tried it yesterday. So I shifted to if else.

**Comment by shashigharti** [comment]
> @shashigharti Yea you might mistakenly have used the same value for testing whether we can set a different value.
> 
> No worries it just needs a quick fix

Yes. I will fix and push the new changes.

**Comment by aivuk** [comment]
> > In your setter logic you could have used the standard Python setattr method. Instead of a lot of if/else you can have something:
> > `setattr(self, '_{}'.format(name), value)`
> 
> This may not work as I tried it yesterday. So I shifted to if else.

Why it didn't work?

**Comment by aivuk** [comment]
> > > In your setter logic you could have used the standard Python setattr method. Instead of a lot of if/else you can have something:
> > > `setattr(self, '_{}'.format(name), value)`
> > 
> > 
> > This may not work as I tried it yesterday. So I shifted to if else.
> 
> Why it didn't work?

Ok, recursion problem, Got it.

**Comment by shashigharti** [comment]
@aivuk @roll 
Thank you for the suggestion, I have made the changes according to your suggestion.

**Review by roll — APPROVED** [review]
Thanks!

**Pull request merged**
