### PR TITLE
Add option to load resource for steps.table_* from dictionary

### PR DESCRIPTION
**Pull request by n0rdlicht**
# Overview

When using `Pipeline()` loaded from a `pipeline.yaml` or `pipeline.json` resources can't be declared inline as a dictionary/object when using `table-merge`, `table-attach`, etc.

Hence this PR initiates a new resource based on the `resource` dictionary, if provided:

```python
...
if isinstance(source, str):
    source = target.package.get_resource(source)
elif isinstance(source, dict):  # extra check
    source = Resource(source)
source.infer()
...
```

Will add a test, if you think this approach works and doesn't break other things.

---

Please preserve this line to notify @roll (lead of this repository)

### CODE REVIEW

**Comment by roll** [comment]
Hi @n0rdlicht,

I think it's a good idea and a clean implementation

**Comment by n0rdlicht** [comment]
Added test for loading resource from dictionary during `steps.table_*` where implemented. Sorry for the additional commits in the PR history. Any good way to drop these or should be fine after merging?

**Comment by roll** [comment]
Sorry, I missed when it became ready for a review. Can you please rebase?

**Comment by n0rdlicht** [comment]
> Sorry, I missed when it became ready for a review. Can you please rebase?

Done :)

**Comment by roll** [comment]
Thanks!

**Pull request merged**
