### PR TITLE
Removed condition for file size

### LINKED ISSUE #756: Normalize bytes/hash calculation between UNIX and Windows?
# Overview

At the moment, it doesn't match. Shall we normalize line endings etc? It's complicated because `python.csv` requires opening files without a universal newline.

On the other hand, the normalization might just be the wrong way to go because it's checksums. This issue requires proper analysis.

PS.
Search for `IS_UNIX` flag in the tests

### PR DESCRIPTION
**Pull request by shashigharti**
- fixes #756

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by shashigharti** [comment]
@roll it is ready for review!

**Review by roll — CHANGES_REQUESTED** [review]
Amazing work @shashigharti!

Can you please enable other test disabled for windows because of this problem?

You can find them searching by `skipif` - https://github.com/frictionlessdata/frictionless-py/blob/main/tests/resource/test_infer.py#L8

**Comment by shashigharti** [comment]
@roll Thank you! . It is ready for the review.

**Review by roll — APPROVED** [review]
Amazing work, thanks!

And great how you had figured out the root cause :tada:

**Pull request merged**
